version: "3"
services:
  db:
    build: ../db
    container_name: recipedb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - recipe-data:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    build: ../api
    container_name: api
    ports:
      - "5000:5000"
#  front:
#    depends_on:
#      - db
#      - api
#    build: ../behaviors
#    container_name: behaviors
#    ports:
#      - "3000:3000"
volumes:
  recipe-data: {}
