version: "3"
services:
  db:
    build: ../db
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - map-data:/var/lib/postgresql/data
  pyapi:
    depends_on:
      - db
    build: ../pyapi
    container_name: pyapi
    ports:
      - "5000:80"
#  front:
#    depends_on:
#      - db
#      - api
#    build: ../behaviors
#    container_name: behaviors
#    ports:
#      - "3000:3000"
volumes:
  map-data: {}
